# Minimizes the "Server" response header (Server Leaks Version Information).
# Apache doesn't support fully blanking this header without a custom module,
# so this reduces it from e.g. "Apache/2.4.25 (Debian)" down to just "Apache".
ServerTokens Prod
ServerSignature Off
